### ISSUE TITLE
Code not working in my sheet , what am I doing wronge

### ISSUE THREAD

**Issue by KairaKilljoy** [fuzzysteve/eve-googledocs-script#10]
I tried to use the code in a google spreadsheet and I believe I'm missing something. I am a total rookie on spreadsheet formulas, please help.

**Comment by Ashisacat** [comment]
It's not a formula, it's a script.

In Sheets, go tools -> script editor.

This should open a new tab/window, into which you should empty the text box and paste in all of the code from one of the .gs files in this repo.

That will create a new formula available to you in sheets, to be called using =FUNCTIONNAME - the function name is listed in the comments at the top of the GS file (or the top of your google scripts editor, if you copied the entire file).

The arguments are also listed in the comments at the top of the file.  For the blueprints .gs, for example:
"
Call this function like:
=loadBlueprints("corp",4324234,"7okqZ1gOyG43243243242342qb2wkyd21C",90926985)
and get all your blueprints loaded into the sheet. I'd suggest doing it on a blank sheet,
rather than in a sheet you have useful information on.
It's 'blueprint ID','location ID','Typeid of blueprint','name of blueprint','which hangar it's in',
'quantity. -2 for a BPC, -1 for a BPO, a number for stacked BPOs',TE,ME,'runs, -1 for a BPO'
"

**Comment by fuzzysteve** [comment]
https://www.youtube.com/watch?v=wNIfpPOOo0M should help.
